---
title: "Materiais"
format: html
---

## Introdução aos materiais

O sucesso do projeto RespiRA assenta na digitalizaçao de instrumentos válidos e na implementação de regras de segurança rigorosas (eCRF). Utilizamos o software REDcap, de forma a garatnir que cada dado inserido pelo paciente ou pelo investigador é fidedigno e útil para o controlo da asma.

## 1. Tratamento de monitorização (eCRF)

A recolha de dados está dividida em 5 formulários principais, cada um com objetivos e validações especificas.

### A. Informação geral e triagem

É o ponto de entrada no estudo. Inclui a atribuição do ID do participante e a verificação do grupo (controlo ou intervenção). O sistema utiliza um mecanismo em que, se o utilizador não autorizar o consentimento informado, o processo de recolha de dados não é executado.

### B. Dados demográficos e elegibilidade

Recolha de perfil básico, nomeadmaente, nome, sexo e morada. Implementámos uma validação automática para a data de nascimento. O sistema apenas permite a inclusão de adultos entre os 18 e os 65 anos, emitindo um alerta de erro caso o participante esteja fora deste intervalo de idades.

### D. Monitorização clínica RespiRA

Este formulário é preenchido periodicamente e inclui indicadores de saúde: *É registado o peso (que pode variar entre 30 e 250kg) e o peak flow (que pode variar entre 50 e 900L/min).* Existem cálculos automáticos em tempo real para o IMC e para o PEF previsto, criando alertas visuais se os valores forem preocupantes. \*Inclui um questionário de 5 a 25 pontos para o Score ACT onde, caso o resultado seja inferior a 20, a app emite um alerta de asma não controlada.

------------------------------------------------------------------------

## 2. Fórmulas de suporte técnico

Para garantir a precisão clínica, o sistema baseia-se nas seguintes equações matemáticas:

**Cálculo do IMC:** $$IMC=\frac{Peso}{Altura^2}$$

**Predição do débito expiratório máximo (PEF previsto):** $$PEF_{previsto}=(Altura\times 5.48) - (Idade\times 0.03)-1.58$$

**Avaliação de progresso(Variação do ACT):** $$\Delta ACT = ACT_{t12}-ACT_{t0}$$

------------------------------------------------------------------------

## 3.Dicionário de dados e segurança

Todas as variáveis críticas relativas à saúde, como sintomas e medicação, têm preenchimento obrigatório para evitar dados em falta. Para além disso, foram configurados alertas automáticos para valores extremos, incentivando o paciente a contactar o médico.

### Resumo da estrutura de dados

| Variável         | Descrição                 | Regras de Validação           |
|:-----------------|:--------------------------|:------------------------------|
| 'weight'         | Peso (kg)                 | Entre 30 e 250                |
| 'pef_value'      | Pico de fluxo expiratório | Entre 50 e 900 L/min          |
| 'act_score'      | Pontuação do teste ACT    | Inteiro entre 5 e 25          |
| 'smoking_status' | Estado tabágico           | Escolha múltipla              |
| 'pack_year'      | Carga tabágica            | Visível se fumador/ex-fumador |

------------------------------------------------------------------------
